name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: check repo
              uses: actions/checkout@v6

            - name: List and Read file
              run: |
                echo "My first Github Actions job"
                ls -ltra
                cat README.md

 